export const surpriseMePrompts = [
    'an armchair in the shape of an avocado',
    'a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers',
    'teddy bears shopping for groceries in Japan, ukiyo-e',
    'an oil painting by Matisse of a humanoid robot playing chess',
    'panda mad scientist mixing sparkling chemicals, digital art',
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    '3D render of a cute tropical fish in an aquarium on a dark blue background, digital art',
    'an astronaut lounging in a tropical resort in space, vaporwave',
    'an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background',
    'a stained glass window depicting a hamburger and french fries',
    'a pencil and watercolor drawing of a bright city in the future with flying cars',
    'a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art',
    'a fortune-telling shiba inu reading your fate in a giant hamburger, digital art',
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    'an oil pastel drawing of an annoyed cat in a spaceship',
    'a painting of a fox in the style of Starry Night',
    'a bowl of soup that looks like a monster, knitted out of wool',
    'A plush toy robot sitting against a yellow wall',
    'A synthwave style sunset above the reflecting water of the sea, digital art',
    'Two futuristic towers with a skybridge covered in lush foliage, digital art',
    'A 3D render of a rainbow colored hot air balloon flying above a reflective lake',
    'A comic book cover of a superhero wearing headphones',
    'A centered explosion of colorful powder on a black background',
    'A photo of a Samoyed dog with its tongue out hugging a white Siamese cat',
    'A photo of a white fur monster standing in a purple room',
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    'A Samurai riding a Horse on Mars, lomography.',
    'A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography',
    'A realistic photograph of a young woman with blue eyes and blonde hair',
    'A man standing in front of a stargate to another dimension',
    'Spongebob Squarepants in the Blair Witch Project',
    'A velociraptor working at a hotdog stand, lomography',
    'A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens',
    'A BBQ that is alive, in the style of a Pixar animated movie',
    'A futuristic cyborg dance club, neon lights',
    'The long-lost Star Wars 1990 Japanese Anime',
    'A hamburger in the shape of a Rubiks cube, professional food photography',
    'A Synthwave Hedgehog, Blade Runner Cyberpunk',
    'An astronaut encountering an alien life form on a distant planet, photography',
    'A Dinosaur exploring Cape Town, photography',
    'A Man falling in Love with his Computer, digital art',
    'A photograph of a cyborg exploring Tokyo at night, lomography',
    'Dracula walking down the street of New York City in the 1920s, black and white photography',
    'Synthwave aeroplane',
    'A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm',
    'A Space Shuttle flying above Cape Town, digital art',
    'A talking tree in a mystical forest',
    'A time-traveling coffee mug with a personality',
    'A secret underwater city inhabited by mermaids and mermen',
    'A magical library where the books come to life at night',
    'A friendly dragon who loves to cook gourmet meals',
    'A steampunk cityscape with floating airships',
    'A group of cats organizing a feline world domination summit',
    'An enchanted mirror that reveals your innermost desires',
    'A whimsical circus on the moon',
    'A mischievous AI assistant causing chaos in a high-tech office',
    'A parallel universe where gravity works in reverse',
    'A colony of tiny, intelligent robots building a miniature city',
    'A sentient robot gardener tending to a garden on a distant planet',
    'A post-apocalyptic world where animals have evolved to have human-like intelligence',
    'A village of talking animals trying to solve a mysterious disappearance',
    'A superhero who can communicate with plants',
    'A hidden portal to a world of giant candy and sweets',
    'A magical door that leads to different historical time periods',
    'A wizards pet owl with the ability to grant wishes',
    'A futuristic city inhabited by friendly aliens',
    'A haunted mansion where the ghosts are friendly and helpful',
    'A time-traveling detective solving crimes throughout history',
    'A sentient computer program exploring the digital realm',
    'A group of intergalactic explorers discovering a new alien species',
    'A talking dog with a talent for solving complex math problems',
    'A friendly alien ambassador trying to make first contact with Earth',
    'A colony of tiny fairies living in a garden',
    'A sentient spaceship with a quirky personality',
    'A mysterious island with hidden treasures and ancient secrets',
    'A forest inhabited by sentient, bioluminescent plants',
    'A futuristic amusement park with mind-bending attractions',
    'A team of adventurers exploring a lost civilization in the jungle',
    'A magical ring with the power to grant wishes',
    'A group of time-traveling historians studying pivotal moments in history',
    'A friendly ghost who helps people find lost objects',
    'A superhero whose superpower is the ability to understand any language',
    'A talking elephant who dreams of becoming a famous painter',
    'A group of kids discovering a hidden cave filled with wonders',
    'A self-driving car navigating rush hour traffic in a smart city',
    'A surgeon using advanced robotic tools to perform a delicate surgery',
    'A bustling spaceport on Mars with interplanetary travelers',
    'A high-speed train traveling through a vacuum tunnel for super-efficient transportation',
    'A futuristic cityscape with holographic billboards and clean energy technology',
    'A virtual reality classroom where students learn in immersive 3D environments',
    'A drone delivery service bringing packages to your doorstep in minutes',
    'A sustainable underwater city designed to combat rising sea levels',
    'A space elevator connecting Earth to a space station for easy access to space',
    'A world where AI-controlled personal assistants manage daily tasks seamlessly',
    'A smart home with IoT devices that anticipate your needs and preferences',
    'A medical lab using nanotechnology to cure diseases at the molecular level',
    'A global network of hyperloop transportation for rapid intercity travel',
    'A wearable device that enhances human capabilities through augmented reality',
    'A sustainable urban farm using vertical agriculture to feed a city',
    'A renewable energy power plant harnessing energy from ocean currents',
    'A city with underground transportation systems to reduce traffic congestion',
    'A 3D-printed skyscraper constructed with advanced materials',
    'A bioengineered forest designed to filter pollution and improve air quality',
    'A world where renewable energy sources have replaced fossil fuels entirely',
    'A hospital with AI-powered diagnosis and treatment recommendations',
    'A space colony on the moon with its own ecosystem and research facilities',
    'A transparent solar panel technology integrated into windows and buildings',
    'A clean energy grid powered by a network of solar and wind farms',
    'A sustainable fashion industry using lab-grown materials and zero waste practices',
    'A future where remote work and telecommuting are the norm',
    'A fully immersive virtual reality travel experience for exploring distant places',
    'A city with advanced waste recycling systems to minimize environmental impact',
    'A network of self-repairing infrastructure using nanobots and AI monitoring',
    'A world where clean drinking water is accessible to every corner of the globe',
    'A global effort to combat climate change and protect endangered ecosystems',
];